### PR TITLE
Documentation changes

### PR DESCRIPTION
**Pull request by OrkoHunter**
1. Update documentation with binary decoding
2. Updates related to organization settings
3. Create release.py for easy in project release

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Fixes #34. @scls19fr Ping.

**Comment by s-celles** [comment]
Generally a package version is available using

```
pkgname.__version__
```

http://stackoverflow.com/questions/458550/standard-way-to-embed-version-into-python-package

**Comment by OrkoHunter** [comment]
Yes, that's more apt. But that would be in the case of `mtalk.__version__`. The release.py file is just one-place-to-change-all file. I'll change it though.

**Comment by s-celles** [comment]
I understand. 

This is how I'm doing on some other packages

https://github.com/scls19fr/pandas_confusion/blob/master/setup.py
https://github.com/scls19fr/pandas_confusion/blob/master/pandas_confusion/version.py

and so `__version__` is available at package level

**Comment by OrkoHunter** [comment]
That's fair. Let's use that.

**Comment by s-celles** [comment]
I didn't know this tip

```
sys.path.insert(0, 'morse_talk')
import release
```

**Comment by s-celles** [comment]
```
In [1]: import morse_talk
In [2]: morse_talk.__version__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-7495ca7322fe> in <module>()
----> 1 morse_talk.__version__

AttributeError: 'module' object has no attribute '__version__'
```

but

```
In [4]: import morse_talk.release
In [5]: morse_talk.release.__version__
Out[5]: '0.2'
```

You might import all from release in `__init__.py`

**Comment by OrkoHunter** [comment]
I was actually doing the change but then the branch was merged. :) 
I'll send another PR.

**Pull request merged**
