### PR TITLE
Fix encoding binary and implement decoding binary

### PR DESCRIPTION
**Pull request by s-celles**
Fix 
https://github.com/OrkoHunter/morse-talk/issues/22
and https://github.com/OrkoHunter/morse-talk/issues/23

Implements decoding binary

Add some tests

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Can you please rebase ? I've activated Travis-CI.

**Comment by OrkoHunter** [comment]
Thanks for the implementation of the binary decode. It looks good. If you wish, consider yourself adding to the `AUTHORS` file.

**Comment by s-celles** [comment]
I think you can merge. But maybe we should add a Travis-CI badge on README.md and improve doc.

**Comment by OrkoHunter** [comment]
Cool. I'll add the badge and work on the doc. Also, I think landscape is creating a lot of noise. I'm disabling it.

**Comment by s-celles** [comment]
I won't (just disable email notification for Landscape)

**Comment by OrkoHunter** [comment]
^ Yes, I disabled comments on Pull Requests only.

**Pull request merged**
