### PR TITLE
CLI

### PR DESCRIPTION
**Pull request by s-celles**
should fix 

https://github.com/morse-talk/morse-talk/issues/39

### CODE REVIEW

**Comment by s-celles** [comment]
Landscape seems to be (quite) happy.
So that's ready to merge.

**Comment by OrkoHunter** [comment]
Cool! Try squashing commits like "minor fix" and then feel free to merge.

**Comment by s-celles** [comment]
I don't feel very confortable with squashing.

```
$ git rebase -i HEAD~10
[detached HEAD 493d51f] CLI tools for tree, plot and sound
 Date: Thu Dec 3 18:15:16 2015 +0100
 8 files changed, 136 insertions(+), 85 deletions(-)
 rename morse_talk/plot.py => bin/mplot (84%)
 mode change 100644 => 100755
 create mode 100755 bin/msound
 create mode 100755 bin/mtree
 rename morse_talk/{plotter.py => plot.py} (96%)
Successfully rebased and updated refs/heads/cli.
(py2)pc:morse-talk scls$ git push
To https://scls19fr@github.com/scls19fr/morse-talk
 ! [rejected]        cli -> cli (non-fast-forward)
error: failed to push some refs to 'https://scls19fr@github.com/scls19fr/morse-talk'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by OrkoHunter** [comment]
Okay, no problem.

**Comment by OrkoHunter** [comment]
@scls19fr The commits were squashed very well. You just needed to do force push. So, instead of `git push`, this needs

```
git push -f
```

Force push is required whenever you change the git history.

**Comment by s-celles** [comment]
thank you for the tip

**Pull request merged**
