### PR TITLE
Some code improvements

### PR DESCRIPTION
**Pull request by kshitij10496**
1. line 86: word- adds more insight to the splitting.
2. line 90: a simpler for loop to find the checkpoints.
3. line 95: for each character in the input message rather than the unknown identifier char.

### CODE REVIEW

**Comment by kshitij10496** [comment]
Okay.
The link is not working.
I had a few suggestions regarding the project.

**Comment by OrkoHunter** [comment]
Make an issue here https://github.com/OrkoHunter/morse-talk/issues
Or you may want to edit the wiki https://github.com/OrkoHunter/morse-talk/wiki

**Comment by OrkoHunter** [comment]
I'm merging this now. Thanks!

**Comment by kshitij10496** [comment]
Where do I give my suggestions ?
Should I make a new page for Suggestions in WIKI?

**Comment by OrkoHunter** [comment]
You can edit the Road map page. Or if you think it as urgent, try making a separate issue.

**Pull request merged**
