### PR TITLE
Improving code

### PR DESCRIPTION
**Pull request by SylvainDe**
As I was quickly looking at your code, I noticed a few things could be improved.

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Thanks!
Could you please squash all the commits into one or two commits with the appropriate message?

**Comment by SylvainDe** [comment]
I could (even though I'd have to check how to do it) but I thought detailling the different steps might be interesting to you.

**Comment by OrkoHunter** [comment]
Yeah very much. However, the details in code changes should be commented in the PR. And the commit name should be just about the work done. You can simply squash all into one! That helps maintaining a clean git history.

**Comment by SylvainDe** [comment]
Done

**Comment by OrkoHunter** [comment]
Thanks!

**Pull request merged**
